console.log("common.js")


var jobsucheJobTitlePatterns = [
    /\bAdministrator\b/g,
    /\bAllrounder\b/g,
    /\bAnalyst\b/g,
    /\bAnwendungsbetreuer\b/g,
    /\bApplikationsbetreuer\b/g,
    /\bAusbildung\b/g,
    /\bAutomation Specialist\b/g,
    /\bArchitect\b/g,
    /\bArchitekt\b/g,
    /\bBerater\b/g,
    /\bCoordinator\b/g,
    /\bData Scientist\b/g,
    /\bDatenbankadministrator\b/g,
    /\bDevOps\b/g,
    /\bKoordinator\b/g,
    /\bLead\b/g,
    /\bManager\b/g,
    /\bNetzwerkadministrator\b/g,
    /\bNetwork Engineer\b/g,
    /\bNetzwerkspezialist\b/g,
    /\bProduct Owner\b/g,
    /\bProjektmanager\b/g,
    /\bProjektleitung\b/g,
    /\bProjektleiter\b/g,
    /\bProzessberater\b/g,
    /\bProzessmanager\b/g,
    /\bQuality Engineer\b/g,
    /\bSecurity Engineer\b/g,
    /\bRequirements Engineer\b/g,
    /\bSoftwarearchitekt\b/g,
    /\bSoftwaretester\b/g,
    /\bSystemadministrator\b/g,
    /\bSystembetreuer\b/g,
    /\bSystemarchitekt\b/g,
    /\bTeamleitung\b/g,
    /\bTestautomatisierer\b/g,
    /\bTestautomatisierung\b/g,
    /\bTestingenieur\b/g,
    /\bTester\b/g,
    /\bTestmanager\b/g,
    /\bVertriebsassistent\b/g,
    /\bWebdesigner\b/g,
    /\bWerkstudent\b/g,
    /\bConsultant\b/g,
    / Senior /g,
    /^Senior\s/g,
    /^Sr\.\s/g
];